all:
  hosts:
    cloud1_admin:
      ansible_host: "{{ lookup('ini', 'VM_IP type=properties file=../.env') }}"
      ansible_user: vburton
      ansible_ssh_private_key_file: ~/.ssh/googlecloud
      ansible_port: 22

    cloud1_app:
      ansible_host: "{{ lookup('ini', 'VM_IP type=properties file=../.env') }}"
      ansible_user: "{{ lookup('ini', 'ANSIBLE_USER type=properties file=../.env') }}"
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_port: 22
      cloud1_domain: "{{ lookup('ini', 'WORDPRESS_URL type=properties file=../.env') }}"

  children:
    prod:
      hosts:
        cloud1_admin:
        cloud1_app: